# Generated by Django 5.2.13 on 2026-04-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=120, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('level', models.CharField(choices=[('info', '信息'), ('warning', '警告'), ('critical', '严重')], default='info', max_length=20, verbose_name='等级')),
                ('is_published', models.BooleanField(default=True, verbose_name='已发布')),
            ],
            options={
                'verbose_name': '通知公告',
                'verbose_name_plural': '通知公告',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('key', models.CharField(max_length=80, unique=True, verbose_name='配置键')),
                ('value', models.TextField(verbose_name='配置值')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='说明')),
                ('is_sensitive', models.BooleanField(default=False, verbose_name='敏感配置')),
            ],
            options={
                'verbose_name': '系统参数',
                'verbose_name_plural': '系统参数',
                'ordering': ['key'],
            },
        ),
    ]
