# Generated by Django 5.2.13 on 2026-04-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EncryptedSecret",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("namespace", models.CharField(max_length=120, verbose_name="命名空间")),
                ("object_id", models.CharField(max_length=64, verbose_name="对象ID")),
                ("field_name", models.CharField(max_length=64, verbose_name="字段名")),
                ("ciphertext", models.TextField(verbose_name="密文")),
            ],
            options={
                "verbose_name": "加密密文",
                "verbose_name_plural": "加密密文",
                "ordering": ["namespace", "object_id", "field_name"],
            },
        ),
        migrations.AddConstraint(
            model_name="encryptedsecret",
            constraint=models.UniqueConstraint(
                fields=("namespace", "object_id", "field_name"),
                name="uniq_encrypted_secret_namespace_object_field",
            ),
        ),
        migrations.AddIndex(
            model_name="encryptedsecret",
            index=models.Index(fields=["namespace", "object_id"], name="idx_secret_namespace_obj"),
        ),
        migrations.AddIndex(
            model_name="encryptedsecret",
            index=models.Index(fields=["updated_at"], name="idx_secret_updated_at"),
        ),
    ]
