# Generated by Django 5.2.13 on 2026-04-17 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Namespace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用'), ('maintenance', '维护中'), ('archived', '已归档')], default='active', max_length=20, verbose_name='状态')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='NameSpace')),
                ('cluster_name', models.CharField(max_length=120, verbose_name='集群')),
                ('environment', models.CharField(choices=[('prod', '生产'), ('staging', '预发'), ('test', '测试'), ('dev', '开发')], default='dev', max_length=20, verbose_name='环境')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='说明')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='namespaces', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': 'NameSpace',
                'verbose_name_plural': 'NameSpace',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PhysicalHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用'), ('maintenance', '维护中'), ('archived', '已归档')], default='active', max_length=20, verbose_name='状态')),
                ('hostname', models.CharField(max_length=120, unique=True, verbose_name='主机名')),
                ('ip_address', models.GenericIPAddressField(verbose_name='管理 IP')),
                ('serial_number', models.CharField(blank=True, max_length=120, verbose_name='序列号')),
                ('rack_position', models.CharField(blank=True, max_length=80, verbose_name='机架位置')),
                ('environment', models.CharField(choices=[('prod', '生产'), ('staging', '预发'), ('test', '测试'), ('dev', '开发')], default='prod', max_length=20, verbose_name='环境')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='说明')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physical_hosts', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '物理机',
                'verbose_name_plural': '物理机',
                'ordering': ['hostname'],
            },
        ),
        migrations.CreateModel(
            name='VirtualMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用'), ('maintenance', '维护中'), ('archived', '已归档')], default='active', max_length=20, verbose_name='状态')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='虚拟机名称')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP 地址')),
                ('cluster', models.CharField(blank=True, max_length=120, verbose_name='集群')),
                ('cpu_cores', models.PositiveIntegerField(default=2, verbose_name='CPU')),
                ('memory_gb', models.PositiveIntegerField(default=4, verbose_name='内存(GB)')),
                ('environment', models.CharField(choices=[('prod', '生产'), ('staging', '预发'), ('test', '测试'), ('dev', '开发')], default='dev', max_length=20, verbose_name='环境')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='说明')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='virtual_machines', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '虚拟机',
                'verbose_name_plural': '虚拟机',
                'ordering': ['name'],
            },
        ),
    ]
