# Generated by Django 5.2.13 on 2026-04-23 10:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0003_namespace_bseip"),
    ]

    operations = [
        migrations.CreateModel(
            name="QualificationManagement",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False, verbose_name="ID")),
                ("qualification_category", models.CharField(blank=True, max_length=100, null=True, verbose_name="资质类别")),
                ("belong_entity", models.CharField(blank=True, max_length=100, null=True, verbose_name="归属主体")),
                ("belong_department", models.CharField(blank=True, max_length=100, null=True, verbose_name="归属部门")),
                ("qualification_name", models.CharField(blank=True, max_length=100, null=True, verbose_name="资质名称")),
                ("manager", models.CharField(blank=True, max_length=100, null=True, verbose_name="管理员")),
                ("usage", models.CharField(blank=True, max_length=100, null=True, verbose_name="用途")),
                ("cost", models.CharField(blank=True, max_length=100, null=True, verbose_name="费用")),
                ("account", models.CharField(blank=True, max_length=100, null=True, verbose_name="账号")),
                ("password", models.CharField(blank=True, max_length=100, null=True, verbose_name="密码（加密存储）")),
                ("status", models.CharField(blank=True, max_length=100, null=True, verbose_name="状态")),
                ("expire_date", models.DateField(blank=True, null=True, verbose_name="到期日")),
                ("remark", models.CharField(blank=True, max_length=200, null=True, verbose_name="备注说明")),
                ("supplier_name", models.CharField(blank=True, max_length=100, null=True, verbose_name="供应商")),
                ("last_update_time", models.DateTimeField(blank=True, null=True, verbose_name="最新修改日期")),
                ("create_time", models.DateTimeField(blank=True, null=True, verbose_name="创建时间")),
            ],
            options={
                "verbose_name": "资质管理",
                "verbose_name_plural": "资质管理",
                "db_table": "qualification_management",
                "ordering": ["-id"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PurchaseDetail",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False, verbose_name="ID")),
                ("create_time", models.DateTimeField(default=django.utils.timezone.now, verbose_name="购买记录创建时间")),
                ("cost_amount", models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name="成本金额")),
                ("expire_date", models.DateTimeField(blank=True, null=True, verbose_name="到期日期")),
                ("remark", models.CharField(blank=True, max_length=200, null=True, verbose_name="补充说明/备注")),
                (
                    "parent",
                    models.ForeignKey(
                        db_column="parent_id",
                        db_constraint=False,
                        on_delete=models.deletion.CASCADE,
                        related_name="purchase_details",
                        to="assets.qualificationmanagement",
                        verbose_name="资质",
                    ),
                ),
            ],
            options={
                "verbose_name": "资质采购明细",
                "verbose_name_plural": "资质采购明细",
                "db_table": "purchase_detail",
                "ordering": ["-id"],
                "managed": False,
            },
        ),
        migrations.AlterModelOptions(
            name="virtualmachine",
            options={"managed": False, "ordering": ["-id"], "verbose_name": "虚拟机资产", "verbose_name_plural": "虚拟机资产"},
        ),
    ]
