# Generated by Django 5.2.13 on 2026-04-28 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_purchasedetail_qualificationmanagement_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='virtualmachine',
            table='assets',
        ),
    ]
