# Generated by Django 5.2.13 on 2026-04-17 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BastionHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用'), ('maintenance', '维护中'), ('archived', '已归档')], default='active', max_length=20, verbose_name='状态')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='堡垒机名称')),
                ('endpoint', models.CharField(max_length=160, verbose_name='访问地址')),
                ('username_hint', models.CharField(blank=True, max_length=80, verbose_name='登录提示')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='说明')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '堡垒机',
                'verbose_name_plural': '堡垒机',
                'ordering': ['name'],
            },
        ),
    ]
