# Generated by Django 5.2.13 on 2026-04-17 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizationScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='范围名称')),
                ('scope_type', models.CharField(choices=[('global', '全局'), ('environment', '环境'), ('resource', '资源')], default='resource', max_length=20, verbose_name='范围类型')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='说明')),
            ],
            options={
                'verbose_name': '授权范围',
                'verbose_name_plural': '授权范围',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用'), ('maintenance', '维护中'), ('archived', '已归档')], default='active', max_length=20, verbose_name='状态')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='模块名称')),
                ('code', models.CharField(max_length=60, unique=True, verbose_name='模块编码')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='说明')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_modules', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Module',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AuthorizationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用'), ('maintenance', '维护中'), ('archived', '已归档')], default='active', max_length=20, verbose_name='状态')),
                ('resource_name', models.CharField(max_length=120, verbose_name='资源对象')),
                ('effective_from', models.DateTimeField(verbose_name='生效时间')),
                ('effective_to', models.DateTimeField(blank=True, null=True, verbose_name='失效时间')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_authorizations', to=settings.AUTH_USER_MODEL, verbose_name='授权人')),
                ('subject_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorization_records', to='accounts.role', verbose_name='角色')),
                ('subject_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorization_records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
                ('scope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorizations', to='bsecp.authorizationscope', verbose_name='范围')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorizations', to='bsecp.module', verbose_name='模块')),
            ],
            options={
                'verbose_name': '授权记录',
                'verbose_name_plural': '授权记录',
                'ordering': ['-effective_from'],
            },
        ),
    ]
