# Generated by Django 5.2.13 on 2026-04-20 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bsecp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorizationrecord',
            options={'managed': False, 'ordering': ['-FId'], 'verbose_name': 'Order Auto Authorization Queue', 'verbose_name_plural': 'Order Auto Authorization Queue'},
        ),
    ]
