# Generated by Django 5.2.13 on 2026-04-20 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bsecp', '0002_alter_authorizationrecord_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='authorizationrecord',
            table='OrderAutoAuthorizationQueue',
        ),
    ]
