# Generated by Django 5.2.13 on 2026-04-17 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用'), ('maintenance', '维护中'), ('archived', '已归档')], default='active', max_length=20, verbose_name='状态')),
                ('domain', models.CharField(max_length=160, unique=True, verbose_name='域名')),
                ('record_type', models.CharField(choices=[('A', 'A'), ('CNAME', 'CNAME')], default='A', max_length=20, verbose_name='记录类型')),
                ('target', models.CharField(max_length=200, verbose_name='解析目标')),
                ('environment', models.CharField(choices=[('prod', '生产'), ('staging', '预发'), ('test', '测试'), ('dev', '开发')], default='test', max_length=20, verbose_name='环境')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='说明')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domain_mappings', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '域名映射',
                'verbose_name_plural': '域名映射',
                'ordering': ['domain'],
            },
        ),
        migrations.CreateModel(
            name='PortMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用'), ('maintenance', '维护中'), ('archived', '已归档')], default='active', max_length=20, verbose_name='状态')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='映射名称')),
                ('source_ip', models.GenericIPAddressField(verbose_name='源 IP')),
                ('source_port', models.PositiveIntegerField(verbose_name='源端口')),
                ('target_ip', models.GenericIPAddressField(verbose_name='目标 IP')),
                ('target_port', models.PositiveIntegerField(verbose_name='目标端口')),
                ('protocol', models.CharField(choices=[('tcp', 'TCP'), ('udp', 'UDP')], default='tcp', max_length=10, verbose_name='协议')),
                ('environment', models.CharField(choices=[('prod', '生产'), ('staging', '预发'), ('test', '测试'), ('dev', '开发')], default='test', max_length=20, verbose_name='环境')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='说明')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='port_mappings', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '端口映射',
                'verbose_name_plural': '端口映射',
                'ordering': ['name'],
            },
        ),
    ]
