# Generated by Django 5.2.13 on 2026-04-17 13:16

from django.db import migrations


CREATE_NAT_MAPPINGS_TABLE_SQL = """
CREATE TABLE `nat_mappings` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键ID，自增',
  `interface` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '网络接口名称（如 eth0、wan1）',
  `protocol` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '协议类型（TCP/UDP）',
  `public_ip` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '公网IP地址',
  `public_port` int NOT NULL COMMENT '公网端口',
  `private_ip` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '内网IP地址',
  `private_port` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '内网端口（支持单端口或端口范围）',
  `created_at` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `idx_interface`(`interface` ASC) USING BTREE,
  INDEX `idx_public`(`public_ip` ASC, `public_port` ASC) USING BTREE
) ENGINE = InnoDB
AUTO_INCREMENT = 327
CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci
ROW_FORMAT = DYNAMIC
COMMENT = 'NAT端口映射表（用于记录公网到内网的端口转发规则）';
"""


def _table_exists(schema_editor, table_name: str) -> bool:
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT COUNT(1)
            FROM information_schema.tables
            WHERE table_schema = DATABASE() AND table_name = %s
            """,
            [table_name],
        )
        row = cursor.fetchone()
        return bool(row and row[0])


def ensure_nat_mappings_table(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return

    has_nat_table = _table_exists(schema_editor, "nat_mappings")
    has_legacy_table = _table_exists(schema_editor, "mappings_portmapping")

    if has_nat_table:
        # Production DB already has the target table; keep existing data.
        return

    if has_legacy_table:
        schema_editor.execute("RENAME TABLE `mappings_portmapping` TO `nat_mappings`;")
        return

    schema_editor.execute(CREATE_NAT_MAPPINGS_TABLE_SQL)


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("mappings", "0003_dnsrecord"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(ensure_nat_mappings_table, reverse_code=migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AlterModelTable(
                    name="portmapping",
                    table="nat_mappings",
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="portmapping",
            options={
                "managed": False,
                "ordering": ["interface", "public_ip", "public_port", "-updated_at"],
                "verbose_name": "端口映射",
                "verbose_name_plural": "端口映射",
            },
        ),
    ]
