# Generated by Django 5.2.13 on 2026-04-17 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用'), ('maintenance', '维护中'), ('archived', '已归档')], default='active', max_length=20, verbose_name='状态')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='监控对象')),
                ('target_type', models.CharField(choices=[('host', '主机'), ('k8s', 'K8S'), ('service', '服务')], default='host', max_length=20, verbose_name='类型')),
                ('endpoint', models.CharField(blank=True, max_length=160, verbose_name='地址')),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True, verbose_name='最近心跳')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='说明')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '监控对象',
                'verbose_name_plural': '监控对象',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledTaskRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用'), ('maintenance', '维护中'), ('archived', '已归档')], default='active', max_length=20, verbose_name='状态')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='任务名称')),
                ('schedule', models.CharField(max_length=80, verbose_name='调度表达式')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='最近执行时间')),
                ('last_duration_ms', models.PositiveIntegerField(default=0, verbose_name='最近耗时(ms)')),
                ('last_result', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('partial', '部分成功')], default='success', max_length=20, verbose_name='最近结果')),
                ('log_excerpt', models.CharField(blank=True, max_length=255, verbose_name='日志摘要')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '定时任务',
                'verbose_name_plural': '定时任务',
                'ordering': ['name'],
            },
        ),
    ]
