# Generated by Django 5.2.13 on 2026-04-17 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppLogIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'INFO'), ('warning', 'WARNING'), ('error', 'ERROR'), ('critical', 'CRITICAL')], default='info', max_length=20, verbose_name='级别')),
                ('module', models.CharField(max_length=50, verbose_name='模块')),
                ('trace_id', models.CharField(blank=True, max_length=32, verbose_name='追踪 ID')),
                ('summary', models.CharField(max_length=255, verbose_name='摘要')),
                ('details', models.TextField(blank=True, verbose_name='详情')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, verbose_name='发生时间')),
            ],
            options={
                'verbose_name': '应用日志',
                'verbose_name_plural': '应用日志',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=120, verbose_name='任务名称')),
                ('module', models.CharField(blank=True, max_length=50, verbose_name='模块')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='参数')),
                ('result', models.CharField(default='success', max_length=30, verbose_name='执行结果')),
                ('error_summary', models.CharField(blank=True, max_length=255, verbose_name='错误摘要')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='耗时(ms)')),
                ('trace_id', models.CharField(blank=True, max_length=32, verbose_name='追踪 ID')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, verbose_name='发生时间')),
            ],
            options={
                'verbose_name': '任务执行日志',
                'verbose_name_plural': '任务执行日志',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='登录账号')),
                ('success', models.BooleanField(default=False, verbose_name='是否成功')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 地址')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='客户端')),
                ('failure_reason', models.CharField(blank=True, max_length=255, verbose_name='失败原因')),
                ('trace_id', models.CharField(blank=True, max_length=32, verbose_name='追踪 ID')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, verbose_name='发生时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '登录日志',
                'verbose_name_plural': '登录日志',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=50, verbose_name='模块')),
                ('action', models.CharField(max_length=50, verbose_name='动作')),
                ('target_type', models.CharField(blank=True, max_length=120, verbose_name='目标类型')),
                ('target_id', models.CharField(blank=True, max_length=50, verbose_name='目标 ID')),
                ('target_display', models.CharField(blank=True, max_length=255, verbose_name='目标显示值')),
                ('request_path', models.CharField(blank=True, max_length=255, verbose_name='请求路径')),
                ('method', models.CharField(blank=True, max_length=10, verbose_name='请求方法')),
                ('request_snapshot', models.JSONField(blank=True, default=dict, verbose_name='请求摘要')),
                ('result', models.CharField(default='success', max_length=30, verbose_name='结果')),
                ('trace_id', models.CharField(blank=True, max_length=32, verbose_name='追踪 ID')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, verbose_name='发生时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '操作审计日志',
                'verbose_name_plural': '操作审计日志',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(max_length=120, verbose_name='资源类型')),
                ('resource_id', models.CharField(max_length=50, verbose_name='资源 ID')),
                ('action', models.CharField(max_length=30, verbose_name='动作')),
                ('changed_fields', models.JSONField(blank=True, default=list, verbose_name='变更字段')),
                ('before_snapshot', models.JSONField(blank=True, default=dict, verbose_name='变更前')),
                ('after_snapshot', models.JSONField(blank=True, default=dict, verbose_name='变更后')),
                ('trace_id', models.CharField(blank=True, max_length=32, verbose_name='追踪 ID')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, verbose_name='发生时间')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '资源变更日志',
                'verbose_name_plural': '资源变更日志',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, verbose_name='账号')),
                ('event_type', models.CharField(choices=[('abnormal_login', '异常登录'), ('lockout', '账号锁定'), ('privilege_violation', '越权访问'), ('sensitive_action', '敏感操作')], max_length=50, verbose_name='事件类型')),
                ('severity', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '严重')], default='medium', max_length=20, verbose_name='等级')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 地址')),
                ('description', models.CharField(max_length=255, verbose_name='描述')),
                ('status', models.CharField(choices=[('open', '待处理'), ('in_progress', '处理中'), ('resolved', '已关闭')], default='open', max_length=20, verbose_name='处理状态')),
                ('trace_id', models.CharField(blank=True, max_length=32, verbose_name='追踪 ID')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, verbose_name='发生时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '安全事件日志',
                'verbose_name_plural': '安全事件日志',
                'ordering': ['-occurred_at'],
            },
        ),
    ]
