# Generated by Django 5.2.13 on 2026-04-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginlog",
            name="private_ip",
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name="内网 IP"),
        ),
        migrations.AddField(
            model_name="loginlog",
            name="public_ip",
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name="公网出口 IP"),
        ),
    ]
