# Generated by Django 5.2.13 on 2026-04-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0002_loginlog_private_ip_loginlog_public_ip"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="loginlog",
            index=models.Index(fields=["occurred_at"], name="idx_loginlog_occurred"),
        ),
        migrations.AddIndex(
            model_name="loginlog",
            index=models.Index(fields=["username", "occurred_at"], name="idx_loginlog_user_time"),
        ),
        migrations.AddIndex(
            model_name="loginlog",
            index=models.Index(fields=["success", "occurred_at"], name="idx_loginlog_success_time"),
        ),
        migrations.AddIndex(
            model_name="operationauditlog",
            index=models.Index(fields=["occurred_at"], name="idx_audit_occurred"),
        ),
        migrations.AddIndex(
            model_name="operationauditlog",
            index=models.Index(fields=["module", "occurred_at"], name="idx_audit_module_time"),
        ),
        migrations.AddIndex(
            model_name="operationauditlog",
            index=models.Index(fields=["result", "occurred_at"], name="idx_audit_result_time"),
        ),
        migrations.AddIndex(
            model_name="applogindex",
            index=models.Index(fields=["occurred_at"], name="idx_applog_occurred"),
        ),
        migrations.AddIndex(
            model_name="applogindex",
            index=models.Index(fields=["module", "occurred_at"], name="idx_applog_module_time"),
        ),
        migrations.AddIndex(
            model_name="applogindex",
            index=models.Index(fields=["level", "occurred_at"], name="idx_applog_level_time"),
        ),
        migrations.AddIndex(
            model_name="taskexecutionlog",
            index=models.Index(fields=["occurred_at"], name="idx_tasklog_occurred"),
        ),
        migrations.AddIndex(
            model_name="taskexecutionlog",
            index=models.Index(fields=["task_name", "occurred_at"], name="idx_tasklog_name_time"),
        ),
        migrations.AddIndex(
            model_name="taskexecutionlog",
            index=models.Index(fields=["result", "occurred_at"], name="idx_tasklog_result_time"),
        ),
        migrations.AddIndex(
            model_name="resourcechangelog",
            index=models.Index(fields=["occurred_at"], name="idx_change_occurred"),
        ),
        migrations.AddIndex(
            model_name="resourcechangelog",
            index=models.Index(fields=["resource_type", "occurred_at"], name="idx_change_type_time"),
        ),
        migrations.AddIndex(
            model_name="resourcechangelog",
            index=models.Index(fields=["resource_id", "occurred_at"], name="idx_change_id_time"),
        ),
        migrations.AddIndex(
            model_name="securityeventlog",
            index=models.Index(fields=["occurred_at"], name="idx_sec_event_occurred"),
        ),
        migrations.AddIndex(
            model_name="securityeventlog",
            index=models.Index(fields=["status", "severity", "occurred_at"], name="idx_sec_status_sev_time"),
        ),
        migrations.AddIndex(
            model_name="securityeventlog",
            index=models.Index(fields=["username", "occurred_at"], name="idx_sec_user_time"),
        ),
    ]
