# Generated by Django 5.2.13 on 2026-04-28 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_alter_securityeventlog_status_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applogindex',
            name='trace_id',
            field=models.CharField(blank=True, max_length=32, verbose_name='追踪ID'),
        ),
        migrations.AlterField(
            model_name='loginlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='本地请求地址'),
        ),
        migrations.AlterField(
            model_name='loginlog',
            name='private_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='内网IP'),
        ),
        migrations.AlterField(
            model_name='loginlog',
            name='public_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='公网出口IP'),
        ),
        migrations.AlterField(
            model_name='loginlog',
            name='trace_id',
            field=models.CharField(blank=True, max_length=32, verbose_name='追踪ID'),
        ),
        migrations.AlterField(
            model_name='operationauditlog',
            name='target_display',
            field=models.CharField(blank=True, max_length=255, verbose_name='对象展示值'),
        ),
        migrations.AlterField(
            model_name='operationauditlog',
            name='target_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='对象ID'),
        ),
        migrations.AlterField(
            model_name='operationauditlog',
            name='target_type',
            field=models.CharField(blank=True, max_length=120, verbose_name='对象类型'),
        ),
        migrations.AlterField(
            model_name='operationauditlog',
            name='trace_id',
            field=models.CharField(blank=True, max_length=32, verbose_name='追踪ID'),
        ),
        migrations.AlterField(
            model_name='resourcechangelog',
            name='resource_id',
            field=models.CharField(max_length=50, verbose_name='资源ID'),
        ),
        migrations.AlterField(
            model_name='resourcechangelog',
            name='trace_id',
            field=models.CharField(blank=True, max_length=32, verbose_name='追踪ID'),
        ),
        migrations.AlterField(
            model_name='securityeventlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址'),
        ),
        migrations.AlterField(
            model_name='securityeventlog',
            name='trace_id',
            field=models.CharField(blank=True, max_length=32, verbose_name='追踪ID'),
        ),
        migrations.AlterField(
            model_name='taskexecutionlog',
            name='trace_id',
            field=models.CharField(blank=True, max_length=32, verbose_name='追踪ID'),
        ),
    ]
